### ISSUE TITLE
Facebook issue

### ISSUE THREAD

**Issue by GrosBourrin** [Mte90/Share-Backported#165] opened 2021-01-13 04:30 UTC
FF 84.0.2 - win10

Hi, i love your webext but i report an issue .
When sharing a webpage link to a contact in facebook messenger it says it can't find the  attachment !
Sorry it's in french but it's the same. i unistalled the extension, reinstalled it but it's the same issue .
i have UBO also as ext. maybe it's a conflict or not...

![image](https://user-images.githubusercontent.com/40931468/104406663-1a378680-5560-11eb-95de-c52c9d1a913c.png)

**Comment by Mte90** [comment] 2021-01-13 13:32
Closing as duplicate of #164

**Closed** 2021-01-18 20:10 UTC
Labels: 🔀 duplicate
